apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-pass
  labels:
    app.kubernetes.io/name: "dev-webapp-team1"  
  namespace: dev-team1
spec:
  encryptedData:
    password: AgA3+EbIyCGpNRZGvERVMCmEbFKRk/KR5Cn2JQgfxCZxVpVWuwrp727WG5XqqkH7KpNq24NaPJyGtb14RkYZKkOgd0eyfP488u1kpZqk9s6UD9irY/xH/Vg/LgNL5MqCUfWM2t2+QhMyvZPDrL3BQjeNxH2Z2v6VGiRUHW5HPpcaXk/ue0pNcGKQt+3DL6xYsX9oum1I3Wdmp6BKo9wKd1DKbnHtwQ4nIcnYMk0ji9wNNPDwcBBn0RlA1TFN+YxH+FJ3hYS/dMmgAuwIaDVupEFlzRk5zK0hDL+ULL4NKj1RobT42jAA6xv2OiJVcdHtVxTojm/wuzwvW5b+X76naIQCmeKPl3YYn9WGLjawqztghddPp6R72XYPE0ypfMshu+ApAKqoikyMFjPvYgPEwbfIP591dlylyUt9edktFrbnEJAsdpQq0VcQRxK6rVMIYearUR62WrNRrbIvd1rOGMDf7UQLGazvJNJtpNCyCvRLhuP80XMMLB9VpNkRSo5v+XG1zSDRqQeQu7yR+YnXJgcCg87dgMNlotU7kWoyAk6E4dNbeqZf/nbtxm29kMxLB3YWslU8AVKiVwKzn9fujQDbIvlvVTk0LGceTlzKs+cXGVkQ19NK3Tj9ng3Oq1Mhm8hjIU5ppNLOVQu/uzVWSEMVkayMLvoATAf1ob+q/KRvyGV5VpL6MzW8h6OagAfhoaWe3qseAz7lCJJZulIOjMJFfy12ZpW+l8XPXmlrtj4hSOjC
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: dev-webapp-team1
      name: mysql-pass
      namespace: dev-team1

