apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "dev-webapp-team1"
  labels:
    app.kubernetes.io/name: "dev-webapp-team1"
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: "dev-webapp-team1"
  componentKinds:
    - group: apps
      kind: Deployment
  addOwnerRef: true
