apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-app
  name: nginx-app
  namespace: project-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: configmap-demo 
                key: MYSQL_HOST
          - name: MEMCACHED_HOST
            valueFrom:
              configMapKeyRef:
                name: configmap-demo 
                key: MEMCACHED_HOST
          - name: SOLR_HOST
            valueFrom:
              configMapKeyRef:
                name: configmap-demo 
                key: SOLR_HOST

